config/routes.rb
Rails.application.routes.draw do
  resources :analises
  resources :funcionarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/analise.rb
class Analise < ApplicationRecord
  belongs_to :funcionario

  validates :processo, :status_analise, :funcionario, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
    has_many :analises

    validates :nome, :cargo, :senha, presence: true
    validates :cpf, presence: true, uniqueness: true

    before_destroy :verificar_analises

    private

    def verificar_analises
        if analises.any?
            errors.add(:base, "Funcionário com análises associadas não pode ser excluído.")
            throw :abort
        end
    end
end

app/controllers/analises_controller.rb
class AnalisesController < ApplicationController
  before_action :set_analise, only: %i[ show edit update destroy ]

  # GET /analises or /analises.json
  def index
    @analises = Analise.all
  end

  # GET /analises/1 or /analises/1.json
  def show
  end

  # GET /analises/new
  def new
    @analise = Analise.new
  end

  # GET /analises/1/edit
  def edit
  end

  # POST /analises or /analises.json
  def create
    @analise = Analise.new(analise_params)

    respond_to do |format|
      if @analise.save
        format.html { redirect_to @analise, notice: "Análise concluída com sucesso." }
        format.json { render :show, status: :created, location: @analise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @analise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analises/1 or /analises/1.json
  def update
    respond_to do |format|
      if @analise.update(analise_params)
        format.html { redirect_to @analise, notice: "Análise atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @analise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @analise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analises/1 or /analises/1.json
  def destroy
    @analise.destroy!

    respond_to do |format|
      format.html { redirect_to analises_path, status: :see_other, notice: "Análise excluída com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analise
      @analise = Analise.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def analise_params
      params.expect(analise: [ :processo, :diploma_nao_emitido_check, :status_matricula_check, :nome_check, :nome_correto, :cpf_check, :cpf_correto, :data_nascimento_check, :data_nascimento_correta, :naturalidade_check, :naturalidade_correta, :nome_pai_check, :nome_pai_correto, :nome_mae_check, :nome_mae_correto, :identidade_check, :identidade_correta, :orgao_expedidor_check, :orgao_expedidor_correto, :uf_check, :uf_correta, :data_expedicao_check, :data_expedicao_correta, :tipo_certidao_check, :tipo_certidao_correto, :cartorio_check, :cartorio_correto, :numero_termo_check, :numero_termo_correto, :folha_check, :folha_correta, :livro_check, :livro_correto, :data_emissao_check, :data_emissao_correta, :matricula_check, :matricula_correta, :email_pessoal_check, :email_pessoal_correto, :cadastro_tcc_check, :cadastro_tcc_correto, :deposito_tcc_check, :ata_defesa_check, :titularidade_professores_check, :nada_consta_check, :autorizacao_funcionamento_check, :doc_rg_check, :doc_cpf_check, :doc_certidao_check, :doc_reservista_check, :doc_titulo_check, :doc_quitacao_check, :doc_historico_check, :doc_certificado_check, :cod_sistec_check, :cod_sistec_correto, :habilitacao_curso_check, :habilitacao_curso_correta, :data_conclusao_check, :data_conclusao_correta, :info_adicional, :status_analise, :funcionario_id ])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  if Rails.env.development?
    skip_before_action :verify_authenticity_token, if: -> { request.host.include?("github.dev") }
  end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]

  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: "Funcionário adicionado com sucesso." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: "Funcionário atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    if @funcionario.analises.any?
      respond_to do |format|
        format.html { redirect_to funcionarios_path, alert: "Funcionário com análises associadas não pode ser excluído." }
        format.json { render json: { error: "Não é possível excluir funcionário com análises associadas." }, status: :unprocessable_entity }
      end
    else
      @funcionario.destroy!

      respond_to do |format|
        format.html { redirect_to funcionarios_path, status: :see_other, notice: "Funcionário excluído com sucesso." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.expect(funcionario: [ :id, :nome, :cpf, :cargo, :senha ])
    end
end

app/helpers/analises_helper.rb
module AnalisesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/analises/_analise.html.erb
<div id="<%= dom_id analise %>">
  <p>
    <strong>Número do Processo</strong>
    <%= analise.processo %>
  </p>

  <p>
    <strong>Diploma Não Emitido</strong>
    <%= analise.diploma_nao_emitido_check %>
  </p>

  <p>
    <strong>Status da Matrícula é "Concluído" ou "Formado"</strong>
    <%= analise.status_matricula_check %>
  </p>

  <p>
    <strong>Nome</strong>
    <%= analise.nome_check %>
  </p>

  <p>
    <strong>Nome Correto</strong>
    <%= analise.nome_correto %>
  </p>

  <p>
    <strong>CPF</strong>
    <%= analise.cpf_check %>
  </p>

  <p>
    <strong>CPF Correto</strong>
    <%= analise.cpf_correto %>
  </p>

  <p>
    <strong>Data de Nascimento</strong>
    <%= analise.data_nascimento_check %>
  </p>

  <p>
    <strong>Data de Nascimento Correta</strong>
    <%= analise.data_nascimento_correta %>
  </p>

  <p>
    <strong>Naturalidade</strong>
    <%= analise.naturalidade_check %>
  </p>

  <p>
    <strong>Naturalidade Correta</strong>
    <%= analise.naturalidade_correta %>
  </p>

  <p>
    <strong>Nome do Pai</strong>
    <%= analise.nome_pai_check %>
  </p>

  <p>
    <strong>Nome do Pai Correto</strong>
    <%= analise.nome_pai_correto %>
  </p>

  <p>
    <strong>Nome da Mãe</strong>
    <%= analise.nome_mae_check %>
  </p>

  <p>
    <strong>Nome da Mãe Correto</strong>
    <%= analise.nome_mae_correto %>
  </p>

  <p>
    <strong>Identidade</strong>
    <%= analise.identidade_check %>
  </p>

  <p>
    <strong>Identidade Correta</strong>
    <%= analise.identidade_correta %>
  </p>

  <p>
    <strong>Órgão Expedidor</strong>
    <%= analise.orgao_expedidor_check %>
  </p>

  <p>
    <strong>Órgão Expedidor Correto</strong>
    <%= analise.orgao_expedidor_correto %>
  </p>

  <p>
    <strong>UF</strong>
    <%= analise.uf_check %>
  </p>

  <p>
    <strong>UF Correta</strong>
    <%= analise.uf_correta %>
  </p>

  <p>
    <strong>Data de Expedição</strong>
    <%= analise.data_expedicao_check %>
  </p>

  <p>
    <strong>Data de Expedição Correta</strong>
    <%= analise.data_expedicao_correta %>
  </p>

  <p>
    <strong>Tipo de Certidão</strong>
    <%= analise.tipo_certidao_check %>
  </p>

  <p>
    <strong>Tipo de Certidão Correto</strong>
    <%= analise.tipo_certidao_correto %>
  </p>

  <p>
    <strong>Cartório</strong>
    <%= analise.cartorio_check %>
  </p>

  <p>
    <strong>Cartório Correto</strong>
    <%= analise.cartorio_correto %>
  </p>

  <p>
    <strong>Número de Termo</strong>
    <%= analise.numero_termo_check %>
  </p>

  <p>
    <strong>Número de Termo Correto</strong>
    <%= analise.numero_termo_correto %>
  </p>

  <p>
    <strong>Folha</strong>
    <%= analise.folha_check %>
  </p>

  <p>
    <strong>Folha Correta</strong>
    <%= analise.folha_correta %>
  </p>

  <p>
    <strong>Livro</strong>
    <%= analise.livro_check %>
  </p>

  <p>
    <strong>Livro Correto</strong>
    <%= analise.livro_correto %>
  </p>

  <p>
    <strong>Data de Emissão</strong>
    <%= analise.data_emissao_check %>
  </p>

  <p>
    <strong>Data de Emissão Correta</strong>
    <%= analise.data_emissao_correta %>
  </p>

  <p>
    <strong>Matrícula</strong>
    <%= analise.matricula_check %>
  </p>

  <p>
    <strong>Matrícula Correta</strong>
    <%= analise.matricula_correta %>
  </p>

  <p>
    <strong>E-mail Pessoal</strong>
    <%= analise.email_pessoal_check %>
  </p>

  <p>
    <strong>E-mail Pessoal Correto</strong>
    <%= analise.email_pessoal_correto %>
  </p>

  <p>
    <strong>Cadastro de TCC</strong>
    <%= analise.cadastro_tcc_check %>
  </p>

  <p>
    <strong>Cadastro de TCC Correto</strong>
    <%= analise.cadastro_tcc_correto %>
  </p>

  <p>
    <strong>Depósito de TCC</strong>
    <%= analise.deposito_tcc_check %>
  </p>

  <p>
    <strong>Ata de Defesa</strong>
    <%= analise.ata_defesa_check %>
  </p>

  <p>
    <strong>Titularidade de Professores</strong>
    <%= analise.titularidade_professores_check %>
  </p>

  <p>
    <strong>Nada Consta</strong>
    <%= analise.nada_consta_check %>
  </p>

  <p>
    <strong>Autorização de Funcionamento</strong>
    <%= analise.autorizacao_funcionamento_check %>
  </p>

  <p>
    <strong>RG</strong>
    <%= analise.doc_rg_check %>
  </p>

  <p>
    <strong>CPF</strong>
    <%= analise.doc_cpf_check %>
  </p>

  <p>
    <strong>Certidão de Registro Civil</strong>
    <%= analise.doc_certidao_check %>
  </p>

  <p>
    <strong>Reservista</strong>
    <%= analise.doc_reservista_check %>
  </p>

  <p>
    <strong>Título</strong>
    <%= analise.doc_titulo_check %>
  </p>

  <p>
    <strong>Certidão de Quitação Eleitoral</strong>
    <%= analise.doc_quitacao_check %>
  </p>

  <p>
    <strong>Histórico Definitivo de Conclusão de Curso</strong>
    <%= analise.doc_historico_check %>
  </p>

  <p>
    <strong>Documento Definitivo de Conclusão de Curso</strong>
    <%= analise.doc_certificado_check %>
  </p>

  <p>
    <strong>Código de Autenticação no SISTEC (somente para cursos técnicos) (3)</strong>
    <%= analise.cod_sistec_check %>
  </p>

  <p>
    <strong>Código SISTEC</strong>
    <%= analise.cod_sistec_correto %>
  </p>

  <p>
    <strong>Habilitação (somente para Licenciatura em Formação Pedagógica para Graduados não Licenciados) (4)</strong>
    <%= analise.habilitacao_curso_check %>
  </p>

  <p>
    <strong>Habilitação Correta</strong>
    <%= analise.habilitacao_curso_correta %>
  </p>

  <p>
    <strong>Data de Conclusão igual ou anterior à data de colação de grau (somente para graduação)</strong>
    <%= analise.data_conclusao_check %>
  </p>

  <p>
    <strong>Data de Conclusão Correta</strong>
    <%= analise.data_conclusao_correta %>
  </p>

  <p>
    <strong>Informação Adicional</strong>
    <%= analise.info_adicional %>
  </p>

  <p>
    <strong>Status da Análise</strong>
    <%= analise.status_analise %>
  </p>

  <p>
    <strong>Funcionário</strong>
    <%= analise.funcionario_id %>
  </p>

</div>

app/views/analises/edit.html.erb
<% content_for :title, "Editando Análise Processual para Emissão de Diploma" %>

<h1>Editando Análise Processual para Emissão de Diploma</h1>

<%= render "form", analise: @analise %>

app/views/analises/index.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-success" role="alert"><%= notice %></div>
<% elsif alert.present? %>
  <div id="alert" class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>

<% content_for :title, "Análises Processuais para Emissão de Diploma" %>

<div class="float-md-end">
  <%= link_to "Realizar Análise", new_analise_path, class: "btn btn-primary" %>
</div>

<h1>Análises Processuais para Emissão de Diploma</h1>

<div id="analises">
  <table class="table table-hover">
    <thead>
      <th>Processo</th>
      <th>Data da Análise</th>
      <th>Data de Atualização</th>
      <th>Status da Análise</th>
      <th>Funcionário</th>
      <th></th>
    </thead>
    <tbody>
      <% @analises.each do |analise| %>
        <tr>
          <td><%= analise.processo %></td>
          <td><%= analise.created_at %></td>
          <td><%= analise.updated_at %></td>
          <td><%= analise.status_analise %></td>
          <td><%= analise.funcionario_id %></td>
          <td>
            <div class="d-grid gap-2">
              <%= link_to analise, class: "btn btn-outline-secondary btn-sm", title: "Exibir Análise" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                  <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"></path>
                  <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"></path>
                </svg>
                <span class="visually-hidden">Exibir Análise</span>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/analises/new.html.erb
<% content_for :title, "Nova Análise Processual para Emissão de Diploma" %>

<h1>Nova Análise Processual para Emissão de Diploma</h1>

<%= render "form", analise: @analise %>

app/views/analises/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @analise %>

<div>
  <%= link_to "Editar", edit_analise_path(@analise), class: "btn btn-primary mb-2" %>
  <%= link_to "Excluir", analise_path(@analise),
      data: { turbo_method: :delete, turbo_confirm: "Confirma a exclusão desta análise?" }, class: "btn btn-danger ms-2 mb-2" %>
  <div class="float-md-end">
    <%= link_to "Voltar para Análises", analises_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(funcionario.errors.count, "erro") %> impediu(ram) que este funcionário fosse salvo:</h4>
      <ul class="mb-0">
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :nome, "Nome Completo", class: "form-label" %>
    <%= form.text_field :nome, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :cpf, "CPF", class: "form-label" %>
    <%= form.text_field :cpf, class: "form-control", placeholder: "000.000.000-00", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :cargo, "Cargo", class: "form-label" %>
    <%= form.text_field :cargo, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :senha, "Senha", class: "form-label" %>
    <%= form.password_field :senha, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.submit @funcionario.new_record? ? "Cadastrar" : "Atualizar", class: "btn btn-primary mb-2" %>
    <% if funcionario.new_record? %>
      <div class="float-md-end">
        <%= link_to "Voltar para Funcionários", funcionarios_path, class: "btn btn-secondary" %>
      </div>
    <% else %>
      <div class="float-md-end">
        <%= link_to "Voltar para Cadastro", @funcionario, class: "btn btn-secondary" %>
        <%= link_to "Voltar para Funcionários", funcionarios_path, class: "btn btn-secondary ms-2" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/funcionarios/_funcionario.html.erb
<div id="<%= dom_id funcionario %>">
  <!-- A classe table estiliza a nossa tabela para deixá-la mais apresentável.
  A classe table-bordered inclui as bordas da tabela e classe table-hover
  muda a cor da linha quando passamos o mouse sobre ela. -->
  <table class="table table-bordered table-hover">
    <thead>
      <th>Nome Completo</th>
      <th>CPF</th>
      <th>Cargo</th>
    </thead>
    <tbody>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.cpf %></td>
        <td><%= funcionario.cargo %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/funcionarios/edit.html.erb
<% content_for :title, "Editando Funcionário" %>

<h1>Editando Funcionário</h1>

<%= render "form", funcionario: @funcionario %>

app/views/funcionarios/index.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-success" role="alert"><%= notice %></div>
<% elsif alert.present? %>
  <div id="alert" class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>

<% content_for :title, "Funcionários" %>

<div class="float-md-end">
  <%= link_to "Adicionar Funcionário", new_funcionario_path, class: "btn btn-primary" %>
</div>

<h1>Funcionários</h1>

<div id="funcionarios">
  <table class="table table-hover">
    <thead>
      <th>Nome Completo</th>
      <th>CPF</th>
      <th>Cargo</th>
      <th></th>
    </thead>
    <tbody>
      <% @funcionarios.each do |funcionario| %>
        <tr>
          <td><%= funcionario.nome %></td>
          <td><%= funcionario.cpf %></td>
          <td><%= funcionario.cargo %></td>
          <td>
            <div class="d-grid gap-2">
              <%= link_to funcionario, class: "btn btn-outline-secondary btn-sm", title: "Exibir Cadastro" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                  <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"></path>
                  <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"></path>
                </svg>
                <span class="visually-hidden">Exibir Cadastro</span>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/funcionarios/new.html.erb
<% content_for :title, "Cadastrar Funcionário" %>

<h1>Cadastrar Funcionário</h1>

<%= render "form", funcionario: @funcionario %>

app/views/funcionarios/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="funcionarios">
  <!-- A classe table estiliza a nossa tabela para deixá-la mais apresentável.
  A classe table-bordered inclui as bordas da tabela e classe table-hover muda
  a cor da linha quando passamos o mouse sobre ela. -->
  <table class="table table-bordered table-hover">
    <thead>
      <th>Nome Completo</th>
      <th>CPF</th>      
      <th>Cargo</th>
      <th>Senha</th>
    </thead>
    <tbody>
      <tr>
        <td><%= @funcionario.nome %></td>
        <td><%= @funcionario.cpf %></td>
        <td><%= @funcionario.cargo %></td>
        <td><%= @funcionario.senha %></td>
      </tr>
    </tbody>
  </table>
</div>

<div>
  <%= link_to "Editar", edit_funcionario_path(@funcionario), class: "btn btn-primary mb-2" %>
  <%= link_to "Excluir", funcionario_path(@funcionario),
      data: { turbo_method: :delete, turbo_confirm: "Confirma a exclusão deste funcionário?" }, class: "btn btn-danger ms-2 mb-2" %>
  <div class="float-md-end">
    <%= link_to "Voltar para Funcionários", funcionarios_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sistema de Análise de Processos para Emissão de Diploma" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <%# Inclua todos os arquivos de folha de estilo em app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <div class="container rounded-corners">
      <%= yield %>
    </div>
  </body>
</html>